# Generated by Django 3.1.3 on 2020-11-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('update_on', models.DateTimeField()),
            ],
        ),
    ]
