# Generated by Django 3.1.3 on 2020-11-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201127_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
