# Generated by Django 3.1.3 on 2020-11-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201127_0931'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpost',
            table='myblogpost',
        ),
    ]
