# Generated by Django 3.1.3 on 2020-11-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201128_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('created_on',)},
        ),
    ]
