# Generated by Django 3.1.3 on 2020-11-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201128_0148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-id',), 'verbose_name_plural': 'My Blog Post'},
        ),
    ]
