# Generated by Django 3.1.3 on 2021-01-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20201128_0210'),
        ('blog', '0008_auto_20210116_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='author.Author'),
        ),
    ]
