# Generated by Django 3.1.3 on 2021-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20201128_0210'),
        ('blog', '0009_auto_20210116_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='authors',
            field=models.ManyToManyField(blank=True, to='author.Author'),
        ),
    ]
