# Generated by Django 3.1.3 on 2020-11-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
